spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bandgar9960/microservice_config_server
          clone-on-start: true

server:
  port: 8085

